# Generated by Django 4.2.6 on 2024-03-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240326_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtable',
            options={'ordering': ['table_number']},
        ),
        migrations.AddField(
            model_name='customtable',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customtable',
            name='table_number',
            field=models.IntegerField(unique=True),
        ),
    ]
