# Generated by Django 4.2.6 on 2024-03-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customtable_options_customtable_is_occupied_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomTable',
            new_name='DiningTable',
        ),
    ]
