# Generated by Django 4.2.6 on 2024-03-29 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
