# Generated by Django 4.2.6 on 2024-04-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('taken', 'Order Taken'), ('kitchen', 'In the Kitchen'), ('ready', 'Order Ready'), ('received', 'Order Received'), ('cancelled', 'Order Cancelled')], default='taken', max_length=10),
        ),
    ]
