# Generated by Django 4.2.6 on 2024-04-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diningtable',
            name='is_occupied',
        ),
        migrations.AddField(
            model_name='diningtable',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=10),
        ),
    ]
