# Generated by Django 4.2.6 on 2024-04-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_diningtable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('taken', 'Order Taken'), ('kitchen', 'Order In the Kitchen'), ('ready', 'Order Ready'), ('received', 'Order Received'), ('cancelled', 'Order Cancelled'), ('checkout', 'Checkout')], default='taken', max_length=10),
        ),
    ]
