# Generated by Django 4.2.6 on 2024-04-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tables', models.PositiveIntegerField(default=10, help_text='Set the number of tables in the restaurant')),
            ],
        ),
    ]
