# Generated by Django 4.2.6 on 2024-04-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_surveyquestion_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
