# Generated by Django 4.2.6 on 2024-04-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_order_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
